#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# WordCount documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  8 14:27:52 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# sys.path.insert(0, os.path.abspath('../source'))

# Local Sphinx extensions live in docs/_ext (see ccos_meta.py).
sys.path.insert(0, os.path.abspath('_ext'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# extensions = ['sphinx.ext.autodoc']
extensions = ['myst_parser', 'sphinx.ext.autosectionlabel', "sphinx_design",
'sphinx.ext.autosectionlabel', 'sphinx_copybutton', 'ccos_meta', 'ccos_changelog']

# Automatically prefix labels with the document name
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']


# The master toctree document.
master_doc = 'index'

# General information about the project.
project = "CharaChorder Docs (Tangent's fork)"
copyright = '2025-2026, CharaChorder (unofficial fork by Tangent)'
author = 'CharaChorder'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = '0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# furo ships a light/dark/auto toggle out of the box (auto follows
# prefers-color-scheme and the choice is remembered in localStorage), and
# drives the per-page "Edit on GitHub" link from these repo settings instead
# of html_context.
html_theme_options = {
    "source_repository": "https://github.com/andy23512/charachorder-docs/",
    "source_branch": "main",
    "source_directory": "docs/",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Lets readers switch the generated CCOS setting tables to another device or
# firmware version without a rebuild. Without JS the cached tables still show.
html_css_files = ['ccos-meta.css', 'ccos-changelog.css']
html_js_files = ['ccos-meta.js']

# Excluded from the build: cached Meta API data consumed by the ccos_meta
# extension, not pages of their own.
exclude_patterns += ['_data']

# Appended HTML page title
html_title = f'{project} v{version}'

# Canonical URL
html_baseurl = 'https://andy23512.github.io/charachorder-docs/'

# Logos/icons
html_logo = 'assets/images/CharaChorder-logo.png'
html_favicon = 'assets/images/favicon.ico'

html_copy_source = False

html_use_opensearch = html_baseurl

def setup(app):
    app.add_css_file('custom.css')


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'CCdocs'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'CharaChorder.tex', 'CharaChorder Documentation',
     'CharaChorder', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'CharaChorder', 'CharaChorder Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'CharaChorder', 'CharaChorder Documentation',
     author, 'CharaChorder', 'CharaChorder Documentation',
     'Miscellaneous'),
]
